#:schema https://yazi-rs.github.io/schemas/theme.json

[mgr]
marker_copied   = { fg = "#98bb6c", bg = "#98bb6c" } # green
marker_cut      = { fg = "#e46876", bg = "#e46876" } # red
marker_marked   = { fg = "#957fb8", bg = "#957fb8" } # magenta
marker_selected = { fg = "#ffa066", bg = "#ffa066" } # cyan

cwd = { fg = "#e6c384" } # yellow

# default bg
count_copied   = { fg = "#1f1f28", bg = "#98bb6c" } # green
count_cut      = { fg = "#1f1f28", bg = "#e46876" } # red
count_selected = { fg = "#1f1f28", bg = "#e6c384" } # yellow

border_symbol = "│"
border_style = { fg = "#dcd7ba"} # white

# hovered file indicator
[indicator]
current = { reversed = true }
preview = { reversed = true }

[tabs]
active   = { reversed = true }
inactive = {}

# status-line
[status]
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# blue - light bg
progress_label  = { fg = "#85a6ea", bg = "#363646", bold = true }
# light bg - default bg
progress_normal = { fg = "#363646", bg = "#1f1f28" }
progress_error  = { fg = "#363646", bg = "#1f1f28" }

perm_type  = { fg = "#98bb6c" } # green
perm_read  = { fg = "#e6c384" } # yellow
perm_write = { fg = "#e82424" } # red
perm_exec  = { fg = "#7aa89f" } # cyan

# default bg
[mode]
normal_main = { fg = "#1f1f28", bg = "#85a6ea", bold = true } # blue
select_main = { fg = "#1f1f28", bg = "#957fb8", bold = true } # magenta
unset_main  = { fg = "#1f1f28", bg = "#e6c384", bold = true } # yellow

[pick]
border   = { fg = "#7fb4ca" } # blue
active   = { fg = "#938aa9", bold = true } # magenta
inactive = {}

[input]
border   = { fg = "#7fb4ca" } # blue
title    = {}
value    = {}
selected = { reversed = true }

[cmp]
border   = { fg = "#7fb4ca" } # blue
active   = { reversed = true }
inactive = {}

[tasks]
border  = { fg = "#7fb4ca" } # blue
title   = {}
hovered = { fg = "#938aa9" } # magenta

[which]
cols = 2
separator = " - "
separator_style = { fg = "#727169" } # darkgrey
mask = { bg = "#16161d" } # dark bg
rest = { fg = "#727169" } # darkgrey
cand = { fg = "#85a6ea" }
desc = { fg = "#565666" }

[help]
on      = { fg = "#7aa89f" } # cyan
run     = { fg = "#938aa9" } # magenta
desc    = {}
hovered = { reversed = true, bold = true }
footer  = { fg = "#090618", bg = "#dcd7ba" } # white

[notify]
title_info  = { fg = "#98bb6c" } # green
title_warn  = { fg = "#e6c384" } # yellow
title_error = { fg = "#e82424" } # red

# files
[filetype]
rules = [
    { mime = "image/*", fg = "#e6c384" },
    { mime = "{audio,video}/*", fg = "#957fb8" },
    { mime = "application/{,g}zip", fg = "#e46876" },
    { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#e46876" },
    { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#6a9589" },
    { url = "*", is = "orphan", fg = "#e46876" },
    { url = "*", is = "exec", fg = "#957fb8" },
    { url = "*/", fg = "#85a6ea"}
]


[icon]

globs = [
  { url = "*.txt", text = "📃"},
  { url = "*.mom", text = "📃"},
  { url = "*.me", text = "📃"},
  { url = "*.ms", text = "📃"},
  { url = "*.png", text = "🖼"},
  { url = "*.webp", text = "🖼"},
  { url = "*.ico", text = "🖼"},
  { url = "*.jpg", text = "📸"},
  { url = "*.jpe", text = "📸"},
  { url = "*.jpeg", text = "📸"},
  { url = "*.gif", text = "🖼"},
  { url = "*.svg", text = "🗺"},
  { url = "*.tif", text = "🖼"},
  { url = "*.tiff", text = "🖼"},
  { url = "*.xcf", text = "🖌"},
  { url = "*.html", text = "🌎"},
  { url = "*.xml", text = "📰"},
  { url = "*.gpg", text = "🔒"},
  { url = "*.css", text = "🎨"},
  { url = "*.pdf", text = "📙"},
  { url = "*.djvu", text = "📚"},
  { url = "*.epub", text = "📚"},
  { url = "*.csv", text = "📓"},
  { url = "*.xlsx", text = "📓"},
  { url = "*.doc", text = "📘"},
  { url = "*.docx", text = "📘"},
  { url = "*.pptx", text = "📒"},
  { url = "*.tex", text = "📜"},
  { url = "*.md", text = "📗"},
  { url = "*.r", text = "📊"},
  { url = "*.R", text = "📊"},
  { url = "*.rmd", text = "📊"},
  { url = "*.Rmd", text = "📊"},
  { url = "*.m", text = "📊"},
  { url = "*.mp3", text = "📻"},
  { url = "*.opus", text = "📻"},
  { url = "*.ogg", text = "📻"},
  { url = "*.m4a", text = "📻"},
  { url = "*.aac", text = "📻"},
  { url = "*.flac", text = "🎼"},
  { url = "*.wav", text = "🎼"},
  { url = "*.mkv", text = "🎥"},
  { url = "*.mp4", text = "🎥"},
  { url = "*.webm", text = "🎥"},
  { url = "*.mpeg", text = "🎥"},
  { url = "*.avi", text = "🎥"},
  { url = "*.mov", text = "🎥"},
  { url = "*.mpg", text = "🎥"},
  { url = "*.wmv", text = "🎥"},
  { url = "*.m4b", text = "🎥"},
  { url = "*.flv", text = "🎥"},
  { url = "*.zip", text = "📦"},
  { url = "*.rar", text = "📦"},
  { url = "*.7z", text = "📦"},
  { url = "*.tar.gz", text = "📦"},
  { url = "*.z64", text = "🎮"},
  { url = "*.v64", text = "🎮"},
  { url = "*.n64", text = "🎮"},
  { url = "*.gba", text = "🎮"},
  { url = "*.nes", text = "🎮"},
  { url = "*.gdi", text = "🎮"},
  { url = "*.1", text = "ℹ"},
  { url = "*.nfo", text = "ℹ"},
  { url = "*.info", text = "ℹ"},
  { url = "*.json", text = "🌵"},
  { url = "*.log", text = "📙"},
  { url = "*.iso", text = "📀"},
  { url = "*.img", text = "📀"},
  { url = "*.bib", text = "🎓"},
  { url = "*.ged", text = "👪"},
  { url = "*.part", text = "💔"},
  { url = "*.torrent", text = "🔽"},
  { url = "*.jar", text = "♨"},
  { url = "*.java", text = "♨"},
  { url = "*.py", text = "🍀"},
  { url = "*.lua", text = "🌸"},
  { url = "*.h", text = "🌲"},
  # { url = "*.c", text = "☘"️},
  # { url = "*.cpp", text = "☘"️},
  { url = "*.hpp", text = "🌳"},
  # { url = "*.zsh", text = "⚙"️},
  { url = "*.pt", text = "🪵"},
  { url = "*.pth", text = "🪵"},
  { url = "*.onnx", text = "🪨"},
  { url = "*.engine", text = "🏠"},
  { url = "*.om", text = "🏠"},
  { url = "*.bmodel", text = "🏠"},
  { url = "*.bin", text = "🏠"},
  { url = "*.param", text = "ℹ"},
  { url = "*.encrypted", text = "🍊"},
]

dirs  = []
exts = []

conds = [
	# Special files
	# { if = "orphan", text = "" },
	# { if = "link", text = "" },
	# { if = "block", text = "" },
	# { if = "char", text = "" },
	# { if = "fifo", text = "" },
	# { if = "sock", text = "" },
	# { if = "sticky", text = "" },
	# { if = "dummy", text = "" },

	{ if = "link", text = "⛓" },

	{ if = "orphan", text = "❌" },

  { if = "hidden & dir", text = "👻" },
	{ if = "dir", text = "📁" },
	{ if = "!dir & exec", text = "🎯" },
	{ if = "!(dir | link)", text = "📃" },

  ]
